### ISSUE TITLE
offset adjustment support?

### ISSUE THREAD

**Issue by cai-lw** [taroxd/RPGMV-Taiko#1]
music and chart doesn't sync in my browser

**Comment by taroxd** [comment]
Press -/=  on the song selection menu, or type `Taiko.offset = x` in Development Tool. You should see the result in the console. (Sorry, I am too lazy to make the UI)

I used some ES6 syntax in this version, so this game will be incompatible with many browsers. 
Only tested on nw.js and chrome 50.
